#Arquivo de configuração do servidor HTTP para o NGINX
#Para o projeto, foi criada a pasta raiz /nginx/, e a pasta /nginx/configs/ contendo esse arquivo e outros quando necessário

http {
        # Basic Settings
        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
  
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
  
        # SSL Settings
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;
        
        # Logging Settings
        access_log /var/log/nginx/access.log;

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;

        #Bloco de Configuração do Servidor
        server {
                listen 80;
                server_name joaoteles.duckdns.org;

                root /nginx/;
                #index index.html;

                location /hls {
                        types {
                                application/x-mpegURL m3u8;
                                video/MP2T ts;
                        }
                }
        }
}
