#Caminho para o arquivo de configuração:
#/etc/nginx/

user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 1024;
        # multi_accept on;
}

include /nginx/configs/http.conf; #Arquivo separado de configuração do servidor HTTP, facilitando qualquer necessidade de alteração futura
include /nginx/configs/rtmp.conf; #Arquivo separado de configuração do serviço de RTMP, facilitando qualquer necessidade de alteração futura
