#Arquivo de configuração do serviço de RTMP para o NGINX

#Bloco de configuração do serviço
rtmp{
        server {
                listen 1935;
                chunk_size 4096;
                #allow publish 127.0.0.1;
                #deny publish all;

                application live {
                        live on;
                        record off;
                        hls on;
                        hls_path /nginx/hls;
                        hls_fragment 1;
                        hls_playlist_length 30;

                        #push ${YT_PATH};
                        #push ${TWITCH_PATH};
                }
        }
}
